name: alarm_clock
description: A plugin to interact with platform Alarm Clock
version: 0.0.1
homepage: https://github.com/mathiasgodwin/alarm_clock

publish_to: 'none'
environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: alarm_clock_android
      ios:
        default_package: alarm_clock_ios

dependencies:
  flutter:
    sdk: flutter
  alarm_clock_android:
    path: ../alarm_clock_android
  alarm_clock_ios:
    path: ../alarm_clock_ios
  alarm_clock_platform_interface:
    path: ../alarm_clock_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.1.4



