name: alarm_clock_ios
description: An implementation of the plugin for iOS platforms
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  alarm_clock_platform_interface:
    path: ../alarm_clock_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AlarmClockIosPlugin
        dartPlugin: AlarmClockIos

