name: alarm_clock_android
description: An implementation of alarm_clock_platform_interface for Android
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  alarm_clock_platform_interface:
    path: ../alarm_clock_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.mathiasgodwin.alarm_clock_android
        pluginClass: AlarmClockAndroidPlugin
        dartPlugin: AlarmClockAndroid
